version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: gh-trs-dev
    container_name: gh-trs-dev
    volumes:
      - ${PWD}:/app
      - /app/target
    environment:
      - RUST_BACKTRACE=1
    restart: on-failure
    working_dir: /app
    command: ["sleep", "infinity"]
